[package]
name = "drain_common"
description = "A static library common for both Drain and Drain's dynamic pages."
version = "0.4.5"
edition = "2021"
repository = "https://github.com/fooooter/drain_common"
license = "LGPL-3.0-or-later"
keywords = ["http", "dynamic", "webdev"]

[dependencies]
